export const siteConfig = {
  title: 'Dawit Admassu | Fullstack Software Engineer',
  description:
    "Hello, I'm Dawit Admassu. I am a fullstack software engineer with over 7 years of experience. I specialize in developing ERP, CRM, medical, and fintech applications, focusing on cloud infrastructure (AWS), backend frameworks like FastAPI and Django, and mobile development using Android.",
  keywords: [
    'Dawit Admassu',
    'Fullstack Software Engineer',
    'AWS',
    'React',
    'Next.js',
    'Web development',
    'FastAPI',
    'Django',
    'Mobile development',
    'Android',
    'Fintech',
    'ERP systems',
    'CRM systems',
    'Cloud computing',
    'JavaScript',
    'Python',
    'Java',
    'C#',
    'Developer',
    'Tech enthusiast',
    'Software engineering',
  ],
  url: 'https://dawitadmassu.com',
};
